steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-custom-image:latest", "."]
logsBucket: "gs://cloudbuild-logs-bucket-newscast-transcriber"
options:
  logging: GCS_ONLY
images:
  - "gcr.io/$PROJECT_ID/my-custom-image:latest"
