# .github/workflows/ci.yml

name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | jq . > gcp-credentials.json
          head -n 5 gcp-credentials.json  # Print the first 5 lines of the JSON for debugging
        shell: bash
        working-directory: terraform

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Plan Terraform Changes
        run: terraform plan -var="project_id=parallel-audio-transcriber"
        working-directory: terraform

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve -var="project_id=parallel-audio-transcriber"
        working-directory: terraform

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build Docker Image
        run: gcloud builds submit --config cloudbuild.yaml .

  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest
