name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest

  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest
    needs: test # Ensure Terraform job runs only if 'test' job passes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Plan Terraform Changes
        run: terraform plan -var="project_id=parallel-audio-transcriber"
        working-directory: terraform

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve -var="project_id=parallel-audio-transcriber"
        working-directory: terraform

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: terraform # Ensure Build job runs only if 'terraform' job passes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Build Docker Image
        run: gcloud builds submit --config cloudbuild.yaml .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Dataflow Job
        run: |
          source venv/bin/activate && python src/main.py \
            --region europe-west2 \
            --runner DataflowRunner \
            --project ${{ secrets.GCP_PROJECT }} \
            --sdk_container_image gcr.io/${{ secrets.GCP_PROJECT }}/dataflow-transcriber-image:latest \
            --sdk_location=container
